### ISSUE TITLE
mkbootisofs produces a broken iso image

### ISSUE THREAD

**Issue by Difrex** [sp00f1ng/boobstrap#2]
Hi,

The problems that I received are the wrong working of the mkbootisofs tool.
* Where can I get a `cdboot.img` file?
* The `locate` is a not core tool. Maybe rewrite this script in a more portable way?

```
mkbootisofs bootimage/ > bootimage.iso
locate: не удалось выполнить stat () «/var/lib/mlocate/mlocate.db»: Нет такого файла или каталога
cat: '': Нет такого файла или каталога
```

An image was created but I can't it to boot. Look at the screenshot.

![2020-06-11_317-35-01](https://user-images.githubusercontent.com/3982213/84400092-483f9b80-ac0a-11ea-9a0a-f4647b2e198d.png)

**Comment by sp00f1ng** [comment]
1. "cdboot.img" is a part "grub2" package, try to "apt install grub-pc-bin" or something in Debian-like distros. Typically its stored in: /usr/lib/grub/i386-pc/cdboot.img. same about efi, "apt install grub-efi-amd64-bin".

2. Agree with locate, I will do "manual" search in grub directories.

**Comment by sp00f1ng** [comment]
checkout.

grub i386-pc files are now checked manually.

`locate` removed from code.

**Comment by Difrex** [comment]
It works! Thank you
