### ISSUE TITLE
lddtree function doesn't work properly

### ISSUE THREAD

**Issue by Difrex** [sp00f1ng/boobstrap#6]
Hi,

I have some issues with the `lddtree` function. This is doesn't work on my system properly.

information:

Boobstrap version: commit 1525cc1995623afd763b84797e6afff428f823c3
OS: Manjaro
Kernel: 5.7.0
Coreutils: 8.32
Shell: `sh` is a symbolic link to the `bash`

There is output of a `sudo mkinitramfs initramfs/ --overlay chroot/ --output $PWD/initrd --squashfs-xz`  command

```
ldd: ./=>: Нет такого файла или каталога
      =>
        Failure []
      /lib64/ld-linux-x86-64.so.2
        Failure []
      /usr/bin/mv
        Failure []
      /usr/lib64/ld-linux-x86-64.so.2
        Failure []
      /usr/lib/ld-linux-x86-64.so.2
        Failure []
      /usr/lib/libacl.so.1
        Failure []
      /usr/lib/libattr.so.1
        Failure []
      /usr/lib/libc.so.6
        Failure []
```

**Comment by Difrex** [comment]
Update:

I update the code to the 96ca50027ec2b142b23b5f6d899d2fdc713ac84e and RED messages was fixed. But I'm still got an error with `no such file or directory` message.

I am not sure about related to this issue or not, but I receive a kernel panic. See a shot.

![Снимок экрана от 2020-06-14 15-44-49](https://user-images.githubusercontent.com/3982213/84593670-03a84000-ae56-11ea-9157-5e6b6efa3fcb.png)

**Comment by Difrex** [comment]
UPD2. Sometimes I got another different kernel panic.

![Снимок экрана от 2020-06-14 15-50-03](https://user-images.githubusercontent.com/3982213/84593809-d27c3f80-ae56-11ea-98e2-4bbebb3dd459.png)

**Comment by sp00f1ng** [comment]
![scrot](https://user-images.githubusercontent.com/66548199/84597934-a52f9180-ae56-11ea-8d11-c97c7a79a2f5.png)
looks like test should passed now.

**Comment by Difrex** [comment]
Yep, the issues with a `mkinitramfs` are fixed now. But I still receive a kernel panic on boot.
![Снимок экрана от 2020-06-14 19-39-19](https://user-images.githubusercontent.com/3982213/84598920-df109000-ae76-11ea-9464-afa7f8bccbd4.png)

This is basic Arch chroot created with the `pacstap chroot base`.

**Comment by sp00f1ng** [comment]
yes, confirm this on real hardware, on FM2 socket PC ISO boots fine, but on AM4 I got same error.
The general problem is big size of initramfs image. mwahaha.
I should move all SquashFS to the ISO root. Don't store in initramfs.
Soon I fixed this problem, will add --all-in-one or something options for select: do store or do not store squashfs images in initrd. I not store, they should be move to ISO.
Thanks and please stand by =)
![20200615_113916](https://user-images.githubusercontent.com/66548199/84621670-5ee53b80-af05-11ea-9c49-feda7efb792d.jpg)

**Comment by sp00f1ng** [comment]
my mistake, I just got two different errors. initrd realy didn't work. hehe. I should go setup another PC for PXE testing. sorry. my fault.

**Comment by sp00f1ng** [comment]
now I know what is "regression update" is mean. haha.

**Comment by sp00f1ng** [comment]
lddtree was a regression update.

**Comment by sp00f1ng** [comment]
I should do a litte more smarter lddtree. here is https://www.linux.org.ru/forum/general/15761622 description of the problem.

**Comment by sp00f1ng** [comment]
just have no idea... =| initrd size 2gb+ memory size 4gb

![20200615_185212 1](https://user-images.githubusercontent.com/66548199/84655579-66bfd280-af3b-11ea-99ea-bdecb6bf574c.jpg)

**Comment by sp00f1ng** [comment]
only one way left: put all system data on ISO. initrd must be small as possible. no more than... 200mb or something.

**Comment by sp00f1ng** [comment]
https://github.com/sp00f1ng/boobstrap/commit/cb0fd48acfc71b38b0c68497f5839f729cbb91b1
