### ISSUE TITLE
Strange behavior with --help option

### ISSUE THREAD

**Issue by Difrex** [sp00f1ng/boobstrap#7]
Hi,

Steps to reproduce:

* Run `mkinitramfs --help` and look at a output

**Comment by sp00f1ng** [comment]
haha yes its a cpio of the current directory to stdout, by default mkinitramfs does: mkinitramfs . > filename, but file is not specified, so output to the terminal. will fix it.

**Comment by Difrex** [comment]
Fixed in the latest release.
